name: raftlabs_assignment
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  http: ^0.13.5
  get_it: ^7.2.0
  flutter_screenutil: ^5.5.3+2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  permission_handler: ^10.0.0
  json_annotation: ^4.6.0
  freezed_annotation: ^2.1.0
  injectable: ^1.5.3
  lottie: ^1.4.1
  dartz: ^0.10.1
  connectivity_plus: ^2.3.6
  location: ^4.4.0
  audio_service: ^0.18.7
  just_audio: ^0.9.28
  webview_flutter: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.2.0
  freezed: ^2.1.0+1
  hive_generator: ^1.1.3
  injectable_generator: ^1.5.4
  flutter_lints: ^2.0.0
  json_serializable: ^6.3.1

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/json/
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
